### ISSUE TITLE
Disabling Account Signup Option

### ISSUE THREAD

**Issue by ZMOtech-ca** [farisc0de/Uploady#38]
Just installed v3.0.13, and I'm wanting to disable the ability for new accounts to be created, as this instance is being used for private purposes and isn't open to the public.

Short of editing the login.php file to manually remove the account sign up link, is there another way to disable this?

**Comment by farisc0de** [comment]
Done, check the latest commit.

**Comment by ZMOtech-ca** [comment]
Would I need to do a fresh install with the latest commit, or can I simply replace the existing files that reside in the web root folder of the domain that hosts this script?

**Comment by farisc0de** [comment]
Ideally, yes, but you can replace the files, and if you have access to the database, just add a new value to the settings table

setting_key: disable_signup
setting_value: true

This is to make it work, then you can configure it from the application settings on the admin dashboard.

**Comment by ZMOtech-ca** [comment]
Thank you again for adding this feature.

I've just installed the current release of the script onto a different install, and saw the option to disable public signups. I enabled this feature, however it still shows the "Sign Up" button, as much as clicking it just redirects to the login page.

Any way this can be removed outright when public signups are disabled?

![Image](https://github.com/user-attachments/assets/d3de1135-8e52-42c9-99a7-16166b2b92e5)

**Comment by farisc0de** [comment]
Done. check the latest commit
